load(":tool_rules.bzl", "get_rustc_cfg")

prelude = native

get_rustc_cfg(
    name = "rustc_cfg",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "rustc_action",
    main = "rustc_action.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "rustdoc_test_with_resources",
    main = "rustdoc_test_with_resources.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "failure_filter_action",
    main = "failure_filter_action.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "concat",
    main = "concat.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "transitive_dependency_symlinks",
    main = "transitive_dependency_symlinks.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "get_rustc_cfg",
    main = "get_rustc_cfg.py",
    visibility = [],
)

prelude.python_bootstrap_binary(
    name = "buildscript_run",
    main = "buildscript_run.py",
    visibility = ["PUBLIC"],
)
