
toolchain_alias(
    name = 'genrule',
    actual = 'toolchains//genrule:genrule',
)

toolchain_alias(
    name = 'python_bootstrap',
    actual = 'toolchains//python-bootstrap:python_bootstrap',
)

toolchain_alias(
    name = 'rust',
    actual = 'toolchains//rust:rust',
)

toolchain_alias(
    name = 'cxx',
    actual = 'toolchains//cxx:cxx',
)

toolchain_alias(
    name = 'deno',
    actual = 'toolchains//deno:deno',
)
