// Copyright 2022 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::io::Result;
use std::path::Path;

fn main() -> Result<()> {
    let input = [
        "git_store.proto",
        "local_store.proto",
        "op_store.proto",
        "working_copy.proto",
    ];

    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let protos_dir = if cfg!(buck_build) {
        // NOTE (aseipp, buck_build): the cargo build allows `../src/protos`
        // like below, but this is really awkward in the buck2 design since
        // directory names are autogenerated. use `src/protos` instead.
        root.join("src").join("protos")
    } else {
        root.parent().unwrap().join("src").join("protos")
    };

    let out_dir = if cfg!(buck_build) {
        // NOTE (aseipp, buck_build): under `cfg(buck_build)` the genrule() that
        // invokes this program will automatically set $OUT, so always use that
        // and fail otherwise.
        std::env::var("OUT")
            .map(|s| Path::new(&s).to_path_buf())
            .expect("OUT environment variable not set during cfg(buck_build)")
    } else {
        protos_dir.clone()
    };

    prost_build::Config::new()
        .out_dir(&out_dir)
        .include_file("mod.rs")
        // For old protoc versions. 3.12.4 needs this, but 3.21.12 doesn't.
        .protoc_arg("--experimental_allow_proto3_optional")
        .compile_protos(
            &input
                .into_iter()
                .map(|x| protos_dir.join(x))
                .collect::<Vec<_>>(),
            &[protos_dir],
        )
}
