# Used by open source projects to support `prelude//`

constraint_setting(
    name = "os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "linux",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "macos",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "windows",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "android",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "ios",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "tvos",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "watchos",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "freebsd",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "fuchsia",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "illumos",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "netbsd",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "wasi",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "none",
    constraint_setting = ":os",
    visibility = ["PUBLIC"],
)
