native.constraint_setting(
    name = "maybe_build_only_native_code",
    visibility = ["PUBLIC"],
)

native.constraint_value(
    name = "build_only_native_code",
    constraint_setting = ":maybe_build_only_native_code",
    visibility = ["PUBLIC"],
)

native.filegroup(
    name = "files",
    srcs = glob(
        ["**"],
    ),
    visibility = ["PUBLIC"],
)
